name: Daily Bible Verse Bot (Nest.js)

on:
  schedule:
    # Runs every day at 07:30 UTC. Adjust as needed.
    - cron: '30 7 * * *'

  workflow_dispatch: # Allows manual runs

jobs:
  send-verse:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run the send verse task
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: npm run task:send-verse
